---
- name: Using Ansible to install Datadog Agent on EC2
  hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent
  
  vars:
    datadog_api_key: "e12d4a18747cf40888ac708680072b9a"
    datadog_site: "us5.datadoghq.com"
    datadog_apm_instrumentation_enabled: "all"
    key_name: web-dev-key

