---
- name: Using Ansible to install Datadog Agent on EC2
  hosts: localhost
  connection: local
  gather_facts: True
  become: yes

  tasks:
    - name: Import the Datadog Agent role from the Datadog collection
	  import_role:
	    name: datadog.dd.agent
  
  vars:
    datadog_api_key: "13dfc8fbf655a4fc457df254b8b42c94"
    datadog_site: "datadoghq.com"
    datadog_apm_instrumentation_enabled: "all"
    key_name: web-dev-key